included:
  - BestMovies
  - BestMoviesTests
  - BestMoviesUITests
excluded:
  - .build
analyzer_rules:
  - unused_declaration
  - unused_import
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_is_empty
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  - let_var_whitespace
  - lower_acl_than_parent
  - toggle_bool
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

disabled_rules:
  - multiple_closures_with_trailing_closure

line_length: 200

nesting:
  type_level:
    warning: 3
    error: 3
  function_level:
    warning: 3
    error: 5

type_name:
  min_length: 3
  max_length: 60
type_body_length: 500
function_parameter_count:
  warning: 5
  error: 7
large_tuple: 4
