included:
  - BestMovies
  - BestMoviesTests
  - BestMoviesUITests
excluded:
  - .build
analyzer_rules:
  - unused_declaration
  - unused_import
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_fill_count
  - contains_over_filter_is_empty
  - contains_over_first_is_not_nill
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  - let_var_whitespace
  - lower_acl_than_parent
  - operator_use_whitespace
  - toggle_bool
  - unneded_parentheses_in_closure_argument
  - unwoned_variable_capture
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

line_length:
  warning: 120
  error: 160

type_name:
  min_length: 3
  max_length: 60
line_length: 200
  ignores_comments: true
type_body_length: 500
function_parameter_count:
  warning: 5
  error: 7
large_tuple: 4
enum_case_associated_value_count: 8
